Added test whith check ports

diff --git a/diag-domain-controller b/diag-domain-controller
--- a/diag-domain-controller
+++ b/diag-domain-controller
@@ -663,6 +663,86 @@ is_time_synchronization_enabled() {
     return "$retval"
 }
 
+# Checking services that listen on certain ports
+is_ports_listening() {
+    local retval=0
+    local ports=
+    local count=
+    local current=
+    local temp_file=
+
+    ports="53 88 123 135 137 138 139 389 445 464 636 3268 3269"
+    count="$(echo "$ports" | wc -w)"
+    current=1
+
+    for port in $ports; do
+        output="$(ss -tulpn | grep ":$port ")"
+
+        if test -n "$output"; then
+            echo "Port: $port is in use:"
+            unique_entries=""
+            temp_file=$(mktemp)
+            echo "$output" > "$temp_file"
+
+            while IFS= read -r line; do
+                process_name=$(echo "$line" | awk -F'"' '{print $2}' | sed -E 's/\(.*//; s/\[.*//')
+                pid=$(echo "$line" | awk -F'pid=' '{print $2}' | awk -F',' '{print $1}')
+                service_name=$(systemctl status "$pid" 2>/dev/null | head -n1 | awk '{print $2}')
+                entry="$process_name (pid: $pid) - $service_name"
+
+                if ! echo "$unique_entries" | grep -qF "$entry"; then
+                    unique_entries="$unique_entries$entry"$'\n'
+                    echo "$entry"
+
+                    if test "$port" = "53"; then
+                        if test "$service_name" != "bind.service" && test "$service_name" != "samba.service"; then
+                            echo "Error: An invalid service is listening on port $port: $service_name"
+                            retval=1
+                        fi
+                    fi
+
+                    if test "$port" = "123"; then
+                        if test "$service_name" != "chronyd.service"; then
+                            echo "Warning: port $port listens to a service other than chronyd: $service_name"
+                            if test "$retval" -ne 1; then
+                                retval=2
+                            fi
+                        fi
+                    fi
+
+                    if test "$port" != "53" && test "$port" != "123"; then
+                        if test "$service_name" != "samba.service"; then
+                            echo "Error: An invalid service is listening on port $port: $service_name"
+                            retval=1
+                        fi
+                    fi
+                fi
+            done < "$temp_file"
+
+            rm -f "$temp_file"
+        else
+            if test "$port" = "123"; then
+                echo "Port $port is not use."
+                echo "Warning: Port $port is not listening."
+                if test "$retval" -ne 1; then
+                    retval=2
+                fi
+            else
+                echo "Error: Port $port is not listening."
+                retval=1
+            fi
+        fi
+
+        if test "$current" -lt "$count"; then
+            echo "-------------------------------------------------"
+        fi
+
+        current="$((current + 1))"
+    done
+
+    return "$retval"
+}
+
 task is_domain_info_available
 task is_hostname_correct
 task is_hostname_static_and_transient
@@ -680,6 +760,7 @@ task does_smb_realm_and_krb5_default_realm_it_match
 task are_there_errors_in_samba_databases
 task is_ntp_service_running
 task is_time_synchronization_enabled
+task is_ports_listening
 
 if test "$cmd" = "report"; then
     file_smb="/etc/samba/smb.conf"
